### ISSUE TITLE
Verify entityframework library with webapplicationfactory

### ISSUE THREAD

**Issue by devree-bvb** [VerifyTests/Verify.EntityFramework#435]
#### Is the feature request related to a problem

It seems the verify entityframework library is not usable in tests with a webapplicationfactory. We write integration tests against a webapplicationfactory (https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.testing.webapplicationfactory-1?view=aspnetcore-5.0) to test our complete backend. During setup of the factory, we register our entityframework dbcontext as a singleton, so that we have the same instance outside of the test as inside the test call.
It seems that the verify entityframework library uses asynclocal to record all actions on the dbcontext. This has the final result that the recorded actions inside the api call are not available (and thus verifiable) in the integration test.

#### Describe the solution

Possibly an option / feature flag that the changes on the dbcontext are not recorded on an asynclocal variable, but just a normal (static) variable. This will not work in all scenario's where the library is currently used, but the extra option would enable the library to be used in the webapplication factory scenario.

#### Describe alternatives considered

We have considered the verify sqlserver library, however the verification of individual sql statements is too low level for us and would not be maintanable / verifiable for us in the long term.

**Comment by SimonCropp** [comment]
can u share a stand-alone solution that illustrates this problem?

**Comment by devree-bvb** [comment]
Ok, I will create a test solution for this

**Comment by dracan** [comment]
@devree-bvb Did you end up providing a test solution? I've just tried with WebApplicationFactory too, and am not having much luck sadly. I can get it to work in a standalone test that doesn't use WebApplicationFactory - but if I try to run it against one of my projects that use integrations tests and WebApplicationFactory - I just get `sql: []`.

**Comment by dracan** [comment]
If you didn't get chance - I can knock up a cut-down project demoing this if that's useful @SimonCropp?

**Comment by SimonCropp** [comment]
yep a cut down project would be great

**Comment by dracan** [comment]
@SimonCropp Example showing the issue here...

https://github.com/dracan/VerifyEfExample

**Comment by OskarKlintrot** [comment]
@dracan Have you found a workaround? I have the same issue with `WebApplicationFactory`.

**Comment by dracan** [comment]
@OskarKlintrot - I haven't looked at it since I'm afraid. I'm using Verify quite a lot - but haven't revisited this EF extension because of this issue.

**Comment by OskarKlintrot** [comment]
If I put `EfRecording.StartRecording()` and `.FinishRecording()` just before and after my db query inside my production code, it gives me the log entries. If I remove `.StartRecording()` then `.FinishRecording` throws an exception (even though I have call `.StartRecording()` in my test method):
<img width="545" alt="image" src="https://user-images.githubusercontent.com/6783879/159440759-44a35417-a404-42f9-8679-2590d07f4518.png">
I would assume it has something to do with `LogCommandInterceptor`, it's just that `Start`, `Stop` and the field that stores the log entries are all `static`, so I would assume that it should just work. Or does the `LogCommandInterceptor` along with its static field get garbage collected so that when we resolve a new `DbContext` with new interceptors the field is `null` again? But then I would assume `.FinishRecording()` would throw in the test method and not return an empty list. It's almost like its two different instances of the static field. It feels like there is a gap in my understanding of static, just not sure would I don't understand.

**Comment by SimonCropp** [comment]
the problem here is that the recording feature uses an asynclocal to track state. but webapplicationfactory  spawns a new thread hence the state is not able to be tracked. 

happy to consider any suggestions on how to fix this

**Comment by OskarKlintrot** [comment]
I failed to solve [the riddle](https://nelsonparente.medium.com/a-little-riddle-with-asynclocal-1fd11322067f) :) I noticed you use `ConcurrentBag` inside [`State`](https://github.com/VerifyTests/Verify.EntityFramework/blob/main/src/Verify.EntityFramework/LogCommandInterceptor.cs#L69) so I'm curious what problem `AsyncLocal` solved that couldn't be solved by some concurrent collection (like `ConcurrentBag<T>` or `ConcurrentQueue<T>`)?

**Comment by OskarKlintrot** [comment]
Here's an example that passes all tests: https://github.com/OskarKlintrot/Verify.EntityFramework/blob/main/src/Verify.EntityFramework/LogCommandInterceptor.cs

If you approve I would be happy to open a PR or maybe preferable add a test case that uses `WebApplicationFactory` and then open a PR.

**Comment by SimonCropp** [comment]
@OskarKlintrot happy to consider a PR

**Comment by OskarKlintrot** [comment]
@SimonCropp Great! I added a test case that fails with `AsyncLocal<T>` but passes with the `ConcurrentBag<T>`. A very productive lunch break :)
